import type {
  CategoryRevenue,
  DashboardStats,
  InventoryItem,
  Order,
  Product,
  RevenueDataPoint,
} from "./types";

// Reliable Unsplash photo IDs for desi fashion
const IMG = {
  lawn1: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&q=80",
  lawn2: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&q=80",
  kurti1: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=800&q=80",
  kurti2: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=800&q=80",
  sk1: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&q=80",
  sk2: "https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=800&q=80",
  dupatta1: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=800&q=80",
  dupatta2: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&q=80",
  acc1: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=800&q=80",
  acc2: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&q=80",
  fashion1: "https://images.unsplash.com/photo-1487222477894-8943e31ef7b2?w=800&q=80",
  fashion2: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=800&q=80",
};

export const mockProducts: Product[] = [
  {
    id: "prod-1",
    name: "Floral Lawn 3-Piece Suit",
    slug: "floral-lawn-3-piece-suit",
    description:
      "A breezy printed lawn suit with delicate floral motifs, perfect for summer gatherings and everyday elegance.",
    material: "100% Premium Lawn Cotton",
    care: "Machine wash cold. Iron on low heat. Do not bleach.",
    shipping: "Ships within 2-3 business days. Free shipping on orders over PKR 5,000.",
    category: "Lawn",
    brand: "Sapphire",
    price: 4500,
    compareAtPrice: 5500,
    images: [IMG.lawn1, IMG.lawn2],
    colors: ["Pink", "White", "Green"],
    sizes: ["S", "M", "L", "XL"],
    stock: 24,
    lowStockThreshold: 5,
    sku: "WF-LWN-001",
    isNewArrival: true,
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 42,
    createdAt: "2026-06-15T10:00:00Z",
  },
  {
    id: "prod-2",
    name: "Embroidered Chiffon Dupatta",
    slug: "embroidered-chiffon-dupatta",
    description:
      "Sheer chiffon dupatta with hand-embroidered border and subtle sequin detailing for festive occasions.",
    material: "Pure Chiffon with Embroidery",
    care: "Dry clean recommended. Hand wash gently if needed.",
    shipping: "Ships within 1-2 business days.",
    category: "Dupattas",
    brand: "Maria B",
    price: 2800,
    images: [IMG.dupatta1, IMG.dupatta2],
    colors: ["Gold", "Maroon", "Navy"],
    sizes: ["One Size"],
    stock: 18,
    lowStockThreshold: 5,
    sku: "WF-DUP-002",
    isNewArrival: true,
    isBestSeller: false,
    rating: 4.6,
    reviewCount: 28,
    createdAt: "2026-06-20T10:00:00Z",
  },
  {
    id: "prod-3",
    name: "Classic Shalwar Kameez Set",
    slug: "classic-shalwar-kameez-set",
    description:
      "Timeless shalwar kameez in rich jacquard fabric with contrast piping and matching dupatta.",
    material: "Jacquard Blend",
    care: "Dry clean only for best results.",
    shipping: "Ships within 3-5 business days.",
    category: "Shalwar Kameez",
    brand: "Khaadi",
    price: 8900,
    compareAtPrice: 10500,
    images: [IMG.sk1, IMG.sk2],
    colors: ["Maroon", "Navy", "Black"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: 12,
    lowStockThreshold: 3,
    sku: "WF-SK-003",
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 67,
    createdAt: "2026-05-10T10:00:00Z",
  },
  {
    id: "prod-4",
    name: "Printed Kurti with Palazzo",
    slug: "printed-kurti-with-palazzo",
    description:
      "Comfortable A-line kurti paired with wide-leg palazzo pants. Ideal for casual outings and work.",
    material: "Viscose Rayon",
    care: "Machine wash gentle cycle. Hang dry.",
    shipping: "Ships within 2-3 business days.",
    category: "Kurtis",
    brand: "Alkaram",
    price: 3200,
    images: [IMG.kurti1, IMG.kurti2],
    colors: ["Blue", "Beige", "White"],
    sizes: ["XS", "S", "M", "L", "XL"],
    stock: 30,
    lowStockThreshold: 5,
    sku: "WF-KRT-004",
    isNewArrival: true,
    isBestSeller: true,
    rating: 4.5,
    reviewCount: 35,
    createdAt: "2026-06-25T10:00:00Z",
  },
  {
    id: "prod-5",
    name: "Festive Organza Suit",
    slug: "festive-organza-suit",
    description:
      "Luxurious organza suit with intricate thread work and embellished neckline for wedding season.",
    material: "Organza with Silk Lining",
    care: "Dry clean only.",
    shipping: "Ships within 3-5 business days.",
    category: "Shalwar Kameez",
    brand: "Maria B",
    price: 12500,
    compareAtPrice: 15000,
    images: [IMG.fashion1, IMG.sk1],
    colors: ["Gold", "Pink", "Green"],
    sizes: ["S", "M", "L", "XL"],
    stock: 8,
    lowStockThreshold: 3,
    sku: "WF-SK-005",
    isNewArrival: true,
    isBestSeller: false,
    rating: 4.7,
    reviewCount: 19,
    createdAt: "2026-07-01T10:00:00Z",
  },
  {
    id: "prod-6",
    name: "Casual Cotton Kurti",
    slug: "casual-cotton-kurti",
    description:
      "Everyday cotton kurti with minimal embroidery and side slits for easy movement.",
    material: "100% Cotton",
    care: "Machine wash. Tumble dry low.",
    shipping: "Ships within 1-2 business days.",
    category: "Kurtis",
    brand: "Gul Ahmed",
    price: 2200,
    images: [IMG.kurti2, IMG.kurti1],
    colors: ["White", "Black", "Red"],
    sizes: ["S", "M", "L", "XL"],
    stock: 45,
    lowStockThreshold: 8,
    sku: "WF-KRT-006",
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.4,
    reviewCount: 89,
    createdAt: "2026-04-15T10:00:00Z",
  },
  {
    id: "prod-7",
    name: "Premium Lawn Collection",
    slug: "premium-lawn-collection",
    description:
      "Designer lawn suit with digital print and lace detailing on sleeves and hem.",
    material: "Premium Lawn",
    care: "Hand wash or gentle machine wash.",
    shipping: "Ships within 2-3 business days.",
    category: "Lawn",
    brand: "Gul Ahmed",
    price: 5200,
    images: [IMG.lawn2, IMG.lawn1],
    colors: ["Green", "Blue", "Pink"],
    sizes: ["S", "M", "L", "XL"],
    stock: 3,
    lowStockThreshold: 5,
    sku: "WF-LWN-007",
    isNewArrival: false,
    isBestSeller: false,
    rating: 4.3,
    reviewCount: 22,
    createdAt: "2026-03-20T10:00:00Z",
  },
  {
    id: "prod-8",
    name: "Silk Thread Dupatta",
    slug: "silk-thread-dupatta",
    description:
      "Soft silk dupatta with multicolor thread embroidery, a versatile addition to any outfit.",
    material: "Silk Blend",
    care: "Dry clean recommended.",
    shipping: "Ships within 1-2 business days.",
    category: "Dupattas",
    brand: "Wear Floral",
    price: 3500,
    images: [IMG.dupatta2, IMG.dupatta1],
    colors: ["Red", "Maroon", "Gold"],
    sizes: ["One Size"],
    stock: 15,
    lowStockThreshold: 5,
    sku: "WF-DUP-008",
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.6,
    reviewCount: 31,
    createdAt: "2026-02-10T10:00:00Z",
  },
  {
    id: "prod-9",
    name: "Embellished Clutch Bag",
    slug: "embellished-clutch-bag",
    description:
      "Handcrafted clutch with pearl and crystal embellishments, perfect for weddings and parties.",
    material: "Fabric with Pearl & Crystal Work",
    care: "Wipe clean with soft cloth. Store in dust bag.",
    shipping: "Ships within 1-2 business days.",
    category: "Accessories",
    brand: "Wear Floral",
    price: 1800,
    images: [IMG.acc1, IMG.acc2],
    colors: ["Gold", "Silver", "Pink"],
    sizes: ["One Size"],
    stock: 22,
    lowStockThreshold: 5,
    sku: "WF-ACC-009",
    isNewArrival: true,
    isBestSeller: false,
    rating: 4.5,
    reviewCount: 14,
    createdAt: "2026-06-28T10:00:00Z",
  },
  {
    id: "prod-10",
    name: "Pearl Drop Earrings",
    slug: "pearl-drop-earrings",
    description:
      "Elegant pearl drop earrings with gold-tone finish, a timeless accessory for any desi outfit.",
    material: "Alloy with Faux Pearls",
    care: "Keep away from water and perfume.",
    shipping: "Ships within 1-2 business days.",
    category: "Accessories",
    brand: "Wear Floral",
    price: 950,
    images: [IMG.acc2, IMG.acc1],
    colors: ["Gold", "Silver"],
    sizes: ["One Size"],
    stock: 50,
    lowStockThreshold: 10,
    sku: "WF-ACC-010",
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.7,
    reviewCount: 56,
    createdAt: "2026-01-15T10:00:00Z",
  },
  {
    id: "prod-11",
    name: "Linen Embroidered Kurti",
    slug: "linen-embroidered-kurti",
    description:
      "Breathable linen kurti with front panel embroidery, ideal for warm weather.",
    material: "Pure Linen",
    care: "Machine wash cold. Iron while damp.",
    shipping: "Ships within 2-3 business days.",
    category: "Kurtis",
    brand: "Sapphire",
    price: 3800,
    images: [IMG.kurti2, IMG.fashion2],
    colors: ["Beige", "White", "Blue"],
    sizes: ["S", "M", "L", "XL"],
    stock: 16,
    lowStockThreshold: 5,
    sku: "WF-KRT-011",
    isNewArrival: true,
    isBestSeller: false,
    rating: 4.4,
    reviewCount: 18,
    createdAt: "2026-07-05T10:00:00Z",
  },
  {
    id: "prod-12",
    name: "Velvet Shawl Wrap",
    slug: "velvet-shawl-wrap",
    description:
      "Plush velvet shawl with scalloped edges, adds warmth and glamour to winter ensembles.",
    material: "Velvet",
    care: "Dry clean only.",
    shipping: "Ships within 2-3 business days.",
    category: "Dupattas",
    brand: "Alkaram",
    price: 4200,
    images: [IMG.dupatta1, IMG.fashion1],
    colors: ["Maroon", "Navy", "Black"],
    sizes: ["One Size"],
    stock: 2,
    lowStockThreshold: 5,
    sku: "WF-DUP-012",
    isNewArrival: false,
    isBestSeller: false,
    rating: 4.2,
    reviewCount: 11,
    createdAt: "2026-02-28T10:00:00Z",
  },
];

export const mockOrders: Order[] = [
  {
    id: "ORD-1001",
    customerName: "Ayesha Khan",
    customerEmail: "ayesha.k@email.com",
    customerPhone: "+92 300 1234567",
    shippingAddress: "House 12, Street 5, DHA Phase 6",
    city: "Lahore",
    items: [
      {
        productId: "prod-1",
        name: "Floral Lawn 3-Piece Suit",
        image: IMG.lawn1,
        price: 4500,
        size: "M",
        color: "Pink",
        quantity: 1,
      },
    ],
    subtotal: 4500,
    shipping: 0,
    total: 4500,
    status: "Delivered",
    createdAt: "2026-07-07T14:30:00Z",
    updatedAt: "2026-07-08T10:00:00Z",
  },
  {
    id: "ORD-1002",
    customerName: "Fatima Ali",
    customerEmail: "fatima.a@email.com",
    customerPhone: "+92 321 9876543",
    shippingAddress: "Flat 3B, Clifton Block 2",
    city: "Karachi",
    items: [
      {
        productId: "prod-3",
        name: "Classic Shalwar Kameez Set",
        image: IMG.sk1,
        price: 8900,
        size: "L",
        color: "Maroon",
        quantity: 1,
      },
      {
        productId: "prod-8",
        name: "Silk Thread Dupatta",
        image: IMG.dupatta2,
        price: 3500,
        size: "One Size",
        color: "Red",
        quantity: 1,
      },
    ],
    subtotal: 12400,
    shipping: 0,
    total: 12400,
    status: "Shipped",
    createdAt: "2026-07-08T09:15:00Z",
    updatedAt: "2026-07-08T11:00:00Z",
  },
  {
    id: "ORD-1003",
    customerName: "Sana Malik",
    customerEmail: "sana.m@email.com",
    customerPhone: "+92 333 5551234",
    shippingAddress: "Sector F-7, Markaz",
    city: "Islamabad",
    items: [
      {
        productId: "prod-4",
        name: "Printed Kurti with Palazzo",
        image: IMG.kurti1,
        price: 3200,
        size: "S",
        color: "Blue",
        quantity: 2,
      },
    ],
    subtotal: 6400,
    shipping: 0,
    total: 6400,
    status: "Processing",
    createdAt: "2026-07-08T12:00:00Z",
    updatedAt: "2026-07-08T12:00:00Z",
  },
  {
    id: "ORD-1004",
    customerName: "Hira Sheikh",
    customerEmail: "hira.s@email.com",
    customerPhone: "+92 345 7778899",
    shippingAddress: "Gulberg III, Main Boulevard",
    city: "Lahore",
    items: [
      {
        productId: "prod-6",
        name: "Casual Cotton Kurti",
        image: IMG.kurti2,
        price: 2200,
        size: "M",
        color: "White",
        quantity: 1,
      },
    ],
    subtotal: 2200,
    shipping: 250,
    total: 2450,
    status: "Pending",
    createdAt: "2026-07-08T15:45:00Z",
    updatedAt: "2026-07-08T15:45:00Z",
  },
  {
    id: "ORD-1005",
    customerName: "Zainab Raza",
    customerEmail: "zainab.r@email.com",
    customerPhone: "+92 312 4445566",
    shippingAddress: "Bahria Town Phase 4",
    city: "Rawalpindi",
    items: [
      {
        productId: "prod-5",
        name: "Festive Organza Suit",
        image: IMG.fashion1,
        price: 12500,
        size: "M",
        color: "Gold",
        quantity: 1,
      },
    ],
    subtotal: 12500,
    shipping: 0,
    total: 12500,
    status: "Delivered",
    createdAt: "2026-07-06T11:20:00Z",
    updatedAt: "2026-07-07T16:00:00Z",
  },
  {
    id: "ORD-1006",
    customerName: "Maryam Hussain",
    customerEmail: "maryam.h@email.com",
    customerPhone: "+92 300 8889900",
    shippingAddress: "Model Town, Block C",
    city: "Lahore",
    items: [
      {
        productId: "prod-10",
        name: "Pearl Drop Earrings",
        image: IMG.acc2,
        price: 950,
        size: "One Size",
        color: "Gold",
        quantity: 3,
      },
    ],
    subtotal: 2850,
    shipping: 250,
    total: 3100,
    status: "Cancelled",
    createdAt: "2026-07-05T08:00:00Z",
    updatedAt: "2026-07-05T14:00:00Z",
  },
];

export function buildInventoryFromProducts(products: Product[]): InventoryItem[] {
  return products.flatMap((product) =>
    product.sizes.map((size, index) => ({
      id: `inv-${product.id}-${size}`,
      productId: product.id,
      productName: product.name,
      sku: `${product.sku}-${size}`,
      size,
      stock: Math.max(
        1,
        Math.floor(product.stock / product.sizes.length) +
          (index === 0 ? product.stock % product.sizes.length : 0)
      ),
      lowStockThreshold: product.lowStockThreshold,
    }))
  );
}

export const mockInventory: InventoryItem[] =
  buildInventoryFromProducts(mockProducts);

export const mockRevenueDaily: RevenueDataPoint[] = [
  { date: "Jul 1", revenue: 18500, orders: 4 },
  { date: "Jul 2", revenue: 22300, orders: 5 },
  { date: "Jul 3", revenue: 15600, orders: 3 },
  { date: "Jul 4", revenue: 31200, orders: 7 },
  { date: "Jul 5", revenue: 27800, orders: 6 },
  { date: "Jul 6", revenue: 34500, orders: 8 },
  { date: "Jul 7", revenue: 29100, orders: 6 },
  { date: "Jul 8", revenue: 26350, orders: 5 },
];

export const mockRevenueWeekly: RevenueDataPoint[] = [
  { date: "Week 1", revenue: 98000, orders: 22 },
  { date: "Week 2", revenue: 112500, orders: 26 },
  { date: "Week 3", revenue: 105200, orders: 24 },
  { date: "Week 4", revenue: 125800, orders: 29 },
];

export const mockRevenueMonthly: RevenueDataPoint[] = [
  { date: "Apr", revenue: 385000, orders: 88 },
  { date: "May", revenue: 412000, orders: 95 },
  { date: "Jun", revenue: 445000, orders: 102 },
  { date: "Jul", revenue: 205350, orders: 46 },
];

export const mockCategoryRevenue: CategoryRevenue[] = [
  { category: "Shalwar Kameez", revenue: 285000 },
  { category: "Lawn", revenue: 198000 },
  { category: "Kurtis", revenue: 165000 },
  { category: "Dupattas", revenue: 112000 },
  { category: "Accessories", revenue: 68000 },
];

export function getDashboardStats(
  products: Product[],
  orders: Order[]
): DashboardStats {
  const today = new Date().toISOString().split("T")[0];
  const ordersToday = orders.filter((o) =>
    o.createdAt.startsWith(today)
  ).length;
  const lowStockItems = products.filter(
    (p) => p.stock <= p.lowStockThreshold
  ).length;
  const uniqueCustomers = new Set(orders.map((o) => o.customerEmail)).size;
  const totalRevenue = orders
    .filter((o) => o.status !== "Cancelled")
    .reduce((sum, o) => sum + o.total, 0);

  return {
    totalRevenue,
    ordersToday,
    lowStockItems,
    totalCustomers: uniqueCustomers,
  };
}

export function getProductById(
  products: Product[],
  id: string
): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getRelatedProducts(
  products: Product[],
  product: Product,
  limit = 4
): Product[] {
  return products
    .filter((p) => p.id !== product.id && p.category === product.category)
    .slice(0, limit);
}
